#!/usr/bin/python
# -*- coding: utf8 -*-
import MySQLdb
import time

file = open('/var/www/htmlcert/.htaccess', 'w')
db = MySQLdb.connect(host="host", user="root", passwd="pass", db="dataBase")
cur = db.cursor()
cur.execute("SELECT * FROM blacklist_ip")
result = cur.fetchall()


file.write("""RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f

<FilesMatch "^\.">
    Order allow,deny
    Deny from all
</FilesMatch>

""")

for row in result:
    #'{} {}'.format(1, 2)
    ip = '{} {} {}'.format('Deny from', row[1], '\n')
    file.write(ip)
    #print(ip)

file.close()
